### ISSUE TITLE
Release steps to be automated in github action

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1498]
### Target
Automate the steps from https://github.com/SAP/xsk/wiki/Release-Process in a GitHub action.

Inputs should be:
- Dropdown with options `major, minor, micro`

**Comment by alexkuklin** [comment]
While studying github workflows, release process and corresponding git log, I've noticed few things that need improvement.

### Docker images and buildpacks build and release process

currently, docker images are built based on separate artifact definitions described in POM files, even for slightly different versions.
Because of that, if some change is made to POM, all POM files have to be altered.
For myself I hit that rock while making standalone runtime server version, intended for testing and debugging deployment pipeline.

Issue created for that: #1644 

### Change a way of defining version

Currently version is hardcoded across POM files and is replaced all in one for each release making one big and quite irrelevant diff in commit. This approach have two downsides:
1. irrelevant entries in file change history makes it harder to manage code
2. every single build on forked or branched version have same version as on it is was forked/branched from, making it harder to understand what version of system is being used/deployed/tested/etc.

My proposal on it is described in issue #1645

**Comment by alexkuklin** [comment]
As discussed yesterday, idea on release automation is to make it happen from github interface with options.

I checked up if it is possible to modify repo from within action.

It seems to be quite possible to add repo tag within action and to trigger release build action.

**Comment by alexkuklin** [comment]
github registered release tag can be fetched with

```
curl --silent "https://api.github.com/repos/SAP/xsk/releases/latest" | jq -r .tag_name
v0.16.1
```

I believe there should be more handy way to do that from within github action, will look into it.

**Comment by alexkuklin** [comment]
As I digged into the issue, I found several already existing solutions for github actions for that.

I'm currently hecking them out to see how it is actually working.

**Comment by dpanayotov** [comment]
This issue is closed as the project is no longer maintained
