### ISSUE TITLE
[Tests] HDB Integration test fails

### ISSUE THREAD

**Issue by ivanvolkoff** [SAP/xsk#1516]
Integration test for HDB fails with following message: 
```
Failed tests:   testHDBTableAlterWhenExistingColumnTypeChange(com.sap.xsk.hdb.ds.itest.hdbtable.XSKHDBTableParserHanaITTest)
  testHDBTableAlterWhenAddingNewNotNullableColumn(com.sap.xsk.hdb.ds.itest.hdbtable.XSKHDBTableParserHanaITTest)
  testHDBTableAlterWhenAddingExistingColumnToPKList(com.sap.xsk.hdb.ds.itest.hdbtable.XSKHDBTableParserHanaITTest)
  testHDBTableAlterWhenNotUniqueToUniqueChange(com.sap.xsk.hdb.ds.itest.hdbtable.XSKHDBTableParserHanaITTest)
  testHDBTableAlterWhenAddingNewColumnToPKList(com.sap.xsk.hdb.ds.itest.hdbtable.XSKHDBTableParserHanaITTest)
  testHDBTableAlterWhenCompatibleChange(com.sap.xsk.hdb.ds.itest.hdbtable.XSKHDBTableParserHanaITTest)
  testHDBTableAlterWhenNullableToNotNullableChange(com.sap.xsk.hdb.ds.itest.hdbtable.XSKHDBTableParserHanaITTest)
```

**Comment by vmutafov** [comment]
After further investigation, it seems that most of the errors are related to test assertions like [this one](https://github.com/SAP/xsk/blob/main/integration-tests/engine-hdb/src/test/java/com/sap/xsk/hdb/ds/itest/hdbtable/XSKHDBTableParserHanaITTest.java#L184). We should probably look into the Problems table instead of the logs and maybe we should have an `errorCode` for known possible issues instead of expecting a certain error message string that is prone to changes.

**Comment by dpanayotov** [comment]
to be tracked in #1617
