### ISSUE TITLE
[API] hdb result iterator does not work with index

### ISSUE THREAD

**Issue by dpanayotov** [SAP/xsk#1633]
### Details
The sample query from the documentation https://www.xsk.io/api/hdb/ shows that you can get the value at an index from the current row. This does not however and always returns undefined.

### Steps to reproduce
```javascript
var oConn = $.hdb.getConnection();
var result = oConn.executeQuery('SELECT * FROM "XSK_SAMPLES_PRODUCTS"."products.db::Products.Customers"');
let iterator = result.getIterator();
let metadata = result.metadata.columns;
var output = [];
while (iterator.next()) {
    var currentRow = iterator.value();
    var obj = {};
    for (var i = 0; i < metadata.length; i++) {
        console.log(currentRow); // this prints a key-value object
        console.log(currentRow[i]); // this returns undefined
        obj[metadata[i].name] = currentRow[i];
    }

    output.push(obj);
}
oConn.close();
$.response.contentType = "application/json";
$.response.status = $.net.http.OK;
$.response.setBody(JSON.stringify(output));
```

### Expected
Values of object returned from `iterator.value()` can be accessed with indices as well as with key names. This works in XSC.

**Comment by ivanvolkoff** [comment]
The documentation in the sample above contains a mistake because getting value by index from row object is **unsupported** ( see [XS XSClassic JS API Refference](https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.hdb.ResultSetIterator.html)) Only accessing values by key from a row object is supported. Documentation in xsk.io is edited to correspond to actual functionality. 

resolved in [1bf68a9](https://github.com/SAP/xsk/commit/1bf68a999e04493530b6177d156f1383e42d04da)
