### ISSUE TITLE
[Parsers] Implement Integration Tests for hdbsynonym

### ISSUE THREAD

**Issue by antoanetamh** [SAP/xsk#167]

**Comment by LiliyaLazarova** [comment]
Based on the research that has been made the issue should be closed, because PostgreSQL and MySQL don't support synonyms out of the box and the query CREATE SYNONYM "x" FOR "y" throws an error.
The similar functionality in PostgreSQL could be achieved via using VIEWs or patch that supports synonyms:
https://www.postgresql.org/message-id/kon2r2%24mo6%241@ger.gmane.org
https://www.postgresql.org/message-id/440D446E.7040509@cybertec.at
The similar "view" approach should be used in MySQL for creating synonym, as well as using procedure:
https://blog.mclaughlinsoftware.com/2013/11/24/mysql-synonym/
https://dev.mysql.com/doc/refman/5.7/en/sys-create-synonym-db.html

**Comment by ThuF** [comment]
@LiliyaLazarova  Could it be possible to run the integration tests against a `HANA` database, relying that the connection credentials will be supplied as environment variables? Also such tests should be explicitly enabled with additional parameter:
- `mvn clean install -Dhana-test`
- or `mvn clean install -P hana-tests`

**Comment by LiliyaLazarova** [comment]
Fixed with https://github.com/SAP/xsk/pull/209
