### ISSUE TITLE
[Parsers] xshttpdest

### ISSUE THREAD

**Issue by delchev** [SAP/xsk#35]
**xshttpdest** parser

https://help.sap.com/viewer/400066065a1b46cf91df0ab436404ddc/2.0.03/en-US/6efe500d91ee462c85cce7609646e17a.html

**Comment by ThuF** [comment]
For the integration in the XSK engine, there are two options as of now:
1. Create `XSK_DESTINATIONS` table and store the artefacts data there.
2. Use the SAP BTP Destinations Service to store and retrieve the data:
    - [Destination Service Swagger API](https://api.sap.com/api/SAP_CP_CF_Connectivity_Destination/resource)
    - [Production (Base) URLs (Cloud Foundry)](https://api.sap.com/api/SAP_CP_CF_Connectivity_Destination/overview)

Related XSJS APIs:
- [$.net.http](https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.net.http.html) namespace.
- [$.net.http.Client](https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.net.http.Client.html) API.
- [$.net.http.Destination](https://help.sap.com/doc/3de842783af24336b6305a3c0223a369/2.0.03/en-US/$.net.http.Destination.html) object.

Related to:
- https://github.com/SAP/xsk/issues/19
- https://github.com/SAP/xsk/issues/20

**Comment by dpanayotov** [comment]
# Background
Currently, XSK processes only `host` and `pathPrefix` which are not entirely to [spec](https://help.sap.com/viewer/52715f71adba4aaeb480d946c742d1f6/2.0.03/en-US/6efe500d91ee462c85cce7609646e17a.html)

# Target
Process the following properties when making a request:
* host - mandatory string - must be hostname without protocol prefix or suffix
* port - mandatory integer
* useSSL - optional boolean; default = `true`
if true - set the protocol to `https`; else - `http`
* timeout - optional integer; default = `-1` = no timeout (in milliseconds)
sets the timeout to the client making the request 
* proxyType - optional enum; default = `none`
Possible values - `none`, `http`, `socks`
--> Value `none` does not configure any proxy
--> Value `http` configures the client to use an http proxy 
--> Value `socks` is out of scope for now
* proxyHost - optional string (mandatory if `proxyType` is not `none`)
Use this as the host when configuring the proxy
* proxyPort - optional integer (mandatory if `proxyType` is not `none`)
Use this as the port when configuring the proxy
* authType - optional enum, if not specified default to none
Possible values - [none | basic | AssertionTicket | SamlAssertion | SamlAssertionPropagation]
--> Value `none` does not set Authorization header
--> Value `basic` take the values `username` and `password` --> **TBD from where**
* sslHostCheck - optional boolean (can be set only if `useSSL`=true); default = `true`
--> Value `true` - The SSL certificate subject must match the host name. For example, if SSL server certificate CN=server1.acme.com, then the host parameter must be server1.acme.com. If there is no match, SSL terminates.
--> Value `false` - No host check is performed. Note that if the SSL server certificate is CN=server1.acme.com, and you use “localhost” as a connection parameter (because this certificate is installed on its own server), then this works with sslHostCheck deactivated (sslHostCheck=false).
