### ISSUE TITLE
[Migration Tools] Research what framework should we use for frontend integration tests

### ISSUE THREAD

**Issue by vmutafov** [SAP/xsk#379]
Currently, there are no frontend tests for the Migration perspective. We should research what framework should we use for that kind of tests. Some options are Selenium, Cypress, and Puppeteer but there may be others. The main features desired are:
- ability to run in Github Actions
- easy API for testing - preferably JS or Java-based
- multiple browsers support
- possibilities to embed in the Dirigible
- well supported
- fast tests execution

**Comment by Fluctuationqt** [comment]
# Intro
The following article contains my current research after trying out Selenium, Cypress and Puppeteer with Github Actions.
As a note, in order to setup the integration tests for the Migration perspective, we must first build and run XSK in a nightly Github Action. The tests will execute in a following step in the same action. 
 
# Cypress
Most testing tools like Selenium operate by running tests outside of the browser, by executing remote commands across the network. Cypress runs tests in the browser with a Node server behind it for tasks that require higher privilige. Cypress and the Node process communicate, synchronize, and perform tasks on behalf of each other. Cypress also operates at the network layer by reading and altering web traffic on the fly. 

* Test Runner - a free open-source tool for running the tests, there is a GUI in which you can view the test execution realtime and 'time travel' by clicking on each test command where you can view what the app was before/after the command execution. 
* Dashboard Service - a paid service where Test Runner can uploaded results for a better preview and storage.
* Github Actions - Easily runnable inside a Github Action, because Cypress support a [premade action](https://github.com/cypress-io/github-action) on the dashboard which sets up everything needed to run the tests.
* Cypress offers the ability to record videos and screenshots of the test specs. This feature requires some storage medium. By default screenshots and videos are stored locally on the file system where Test Runner is executed. This is a problem when the tests are running inside a Github Action, because the storage is wiped when the action completes. Thus here the Dashboard Service comes in, offering an easy integration with Github Actions, where you just pass a record key as a Github Secret to the Test Runner and it can send all of it's results, for each test with videos and screenshots to the Cypress Dashboard. There is a possible way to not use the Dashboard service if it is not needed, by writing a Cypress plugin, which can attach to 'after-spec' and send the files, but this is error prone.
* Tests are written in JavaScript only. They are based on Mocha (it, describe, beforeEach). Cypress handles command awaits after command execution automatically, no need to write them explicitly. Cypress automatically includes Bluebird and exposes it as Cypress.Promise. 
* Some use cases require disabling the browser's web security, which changes the test environment and is not a good solution in my opinion. The following two scenarios consider attention:
  * Handling IFrames is currently problematic with Cypress and requires browser Web Secutiry to be turned disabled for cross-origin iframes because browsers adhere to a strict same-origin policy. They are working on a solution, you can read more [here](https://docs.cypress.io/guides/guides/web-security#Cross-origin-iframes).
  * You can visit different superdomains in different tests, but not in the same test. Read more [here](https://docs.cypress.io/guides/guides/web-security#Same-superdomain-per-test).
* Does not support mobile application testing.
* Running tests in chrome and firefox at the same time requires two instances of Cypress, thus two Github Actions.
* Slow on startup time when i tried it in a Github Action, but decent performance while running.
* Runs only with NodeJS
* Not future proof (not a W3C standard like Selenium WebDriver)
* Results can be exported as JSON and many other formats.
* Tied to specific versions of browsers, but supports Chrome, Firefox, Electron, Edge.
* Runs outside of the browser and does not need disabling web security.

> “There are technical limitations to the way Cypress loads and runs the tests, which are covered in https://www.cypress.io/how-it-works Some of the limitations will be removed (iframes, shadow dom support) as we continue, and some limits will probably be there for many years.” - Gleb Bahmutov, distinguished engineer at Cypress

> Problems in cypress that are not problems for Selenium: not supporting multi-tabs, cannot visit two domains of different origin, only inside the browser, unable to drive two browsers

# Selenium
Selenium is the most well known portable framework for testing web applications, consisting of WebDriver, API and Selenium IDE (GUI tool). The API communicates with the WebDriver and automates the browser. Selenium IDE can record user interaction with a web app to generate tests, but it is error prone.
* Supports multiple languages -  Java, C#, Ruby, JavaScript, R and Python.
* Writing tests: Selenium does not have built-in assertion syntax. So we get the final word on that, I used Java with JUnit, but JS with Jasmine is also a posibility, which makes it a good addition to our current Unit tests.
* Supports screenshots, but it does not have built in support for recording videos of the tests.
* No problems with iframe support.
* It doesn't directly support mobile testing, but there are Selenium based tools for mobile app testing.
* Runs outside of the browser.
* Future proof (Web Driver is a W3C standard).
* Not tied to specific browser versions.
* Can run multiple browsers at the same time.
* Supports multi tabs.
* Easiest to integrate into the project structure with maven and run in Github Actions.

# Puppeteer
Puppeteer is a Node library which provides an API to control Chrome or Chromium over the DevTools Protocol. It is written and maintained by the people at Chrome Dev Tools. 

* Supports only chrome/chromium (by default bundled with chromium) Official Firefox support.
* Tied to specific browser builds.
* Had problems setting it up with Github Actions.
* Node.JS library, thus only via Javascript.
* Creators suggest it should not be our only test tool.

The [Github repo for puppeteer](https://github.com/puppeteer/puppeteer) offers some useful FAQ's that answer a lot of our questions. <br>I highlighted some points you should notice:

> Q: What are Puppeteer’s goals and principles?
> - `Provide a slim, canonical library that highlights the capabilities of the DevTools Protocol.`
> - `Provide a reference implementation for similar testing libraries. Eventually, these other frameworks could adopt Puppeteer as their foundational layer.`
> - Grow the adoption of headless/automated browser testing.
> - Help dogfood new DevTools Protocol features... and catch bugs!
> - Learn more about the pain points of automated browser testing and help fill those gaps.

> Q: Is Puppeteer replacing Selenium/WebDriver?
> - No. Both projects are valuable for very different reasons:
> - Selenium/WebDriver focuses on cross-browser automation; its value proposition is a single standard API that works across all major browsers.
> - `Puppeteer focuses on Chromium; its value proposition is richer functionality and higher reliability.`
> - `That said, you can use Puppeteer to run tests against Chromium, e.g. using the community-driven jest-puppeteer. While this probably shouldn’t be your only testing solution, it does have a few good points compared to WebDriver:`
> - `Puppeteer requires zero setup and comes bundled with the Chromium version it works best with, making it very easy to start with. At the end of the day, it’s better to have a few tests running chromium-only, than no tests at all.`
> - Puppeteer has event-driven architecture, which removes a lot of potential flakiness. There’s no need for evil “sleep(1000)” calls in puppeteer scripts.
> - Puppeteer runs headless by default, which makes it fast to run. Puppeteer v1.5.0 also exposes browser contexts, making it possible to efficiently parallelize test execution.
> - Puppeteer shines when it comes to debugging: flip the “headless” bit to false, add “slowMo”, and you’ll see what the browser is doing. You can even open Chrome DevTools to inspect the test environment.

# Results
Most of my effort moved focus on Cypress vs Selenium, after finding out Puppeteer's goals and having issues with it.
My suggestion is that the testing should be done using **Selenium with Jasmine & JUnit** due to:
* Seamless integration into the project structure, builds and Github Actions.
* Less limitations
* More browsers supported (Safari included)
* Can run multiple browsers at the same time
* Future proof

**Comment by ThuF** [comment]
**Outcome**: Selenium selected as preferred framework for UI integration testing.
