### ISSUE TITLE
[Documentation] Code sample for $.request returns an error

### ISSUE THREAD

**Issue by slavipande** [SAP/xsk#514]
**Description of the bug**
The code sample under section Sample Usage on this page returns an error: https://www.xsk.io/api/request/. I've provided a screenshot below for more context.

**To Reproduce**

1. Go to https://www.xsk.io/api/request/
2. Copy the code sample
3. In the xsk trial landscape, create a new project and a new .xsjs file
4. Paste the code sample and save the file.
5. See error in the **Preview** view.

**Expected behavior**
The code sample should work.

**Screenshots**
![2021-09-15_15-24-38](https://user-images.githubusercontent.com/46915717/133432990-fd2fcea6-e447-4cf2-88b3-a870f91370ee.png)

**Desktop:**

- OS: Windows 10
- Browser: Chrome
- Version: Version 93.0.4577.63 (Official Build) (64-bit)

**Comment by aihanrashidov** [comment]
In this case the error response is due to unsupported query path. The sample expects that the query path is `/users` and also an `id` query parameter to be passed.
<img width="373" alt="Screenshot 2021-09-29 at 12 45 19" src="https://user-images.githubusercontent.com/36267628/135244864-1efe65f1-7699-42d9-8d7e-f8a48635efef.png">
I will modify the sample to work for success case without the need to specify a specific path.

**Comment by aihanrashidov** [comment]
Sample update - https://github.com/SAP/xsk/commit/6f287ef55a3f6ead03ebb3074a66c67063d26751

**Comment by delchev** [comment]
confirmed
